# Generated by Django 5.0.3 on 2024-03-17 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='primary_sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislative.legislator'),
        ),
    ]
